version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}
    container_name: "ecommerce-springboot:v${TAG}"
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
