
== Caso de estudio para aplicar asignación de responsabilidades
Esta api tiene un controlador accesible desde la URL
`http://localhost:8080/tienda`.

para correr la api de manera local debe estar en la carpeta *complete* y ejecutar lo siguiente
====
[source,bash]
----
mvn spring-boot:run
----
====
tambien puede ejecutar:

====
[source,bash]
----
./mvnw spring-boot:run
----
====

Tambien puede descargar la imagen y montar la api con docker, con los siguientes pasos:

* Ingrese a la URL `https://github.com/lejito/ecommerce-springboot/pkgs/container/ecommerce-springboot` , alli encontrara un comando para descargar la imagen, con el siguiente formato:
====
[source,bash]
----
docker pull ghcr.io/lejito/ecommerce-springboot:v{version}
----
====
Use la version que se muestra en el paso 1, ya que otras versiones no seran el estado actual de la api.

* use el comando de descarga de la imagen y una vez haya finalizado utilice el siguiente comando para montar la api:
====
[source,bash]
----
docker run --rm --name ecommerce-springboot -p 8080:8080 ghcr.io/lejito/ecommerce-springboot:v{version}
----
====

puede ver los endpoints entrando a la documentacion de swagger:
`http://localhost:8080/swagger-ui.html`

Los siguiente son los endpoints disponibles:

== (GET) obtener usuarios de la tienda
`http://localhost:8080/tienda/usuarios`
====
[source,json]
----
[
    {
        "id": 1,
        "nombre": "",
        "carrito": []
    }
]
----
====
== (GET) obtener productos de la tienda
`http://localhost:8080/tienda/productos`
====
[source,json]
----
[
   {
    "sku": "EA002",
    "nombre": "IPhone",
    "descripcion": "A smartphone made by apple",
    "precio": 625.0,
     "stock":4
  }
]
----
====


== (POST) Agregar un producto al carrito
`http://localhost:8080/usuarios/{id}/carrito`
====
[source,json]
----

----
====


